pipeline{
    agent any

    parameters{
        choice(
            name:"TerraformAction", 
            choices:["apply",'destroy'],
            description:"Choose your terraform action")
    }
      environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages{
        stage("git-checkout"){
           steps{
             git url: "https://github.com/Gotoman12/DevOps-terraform.git", branch: "eks"
           }
        }

        stage("Plan"){
            steps{
                dir('DB'){
                    sh '''
                       terraform init
                       terraform plan -out=tfplan
                       terraform show -no-color tfplan > tfplan.txt
                    '''
                }
            }
        }
       stage('Approval'){
            steps{
                script{
                    def plan = readFile 'DB/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action ${params.TerraformAction}?",
                    parameters: [
                    text
                    (name: 'Plan',
                     description: 'Please review the plan', 
                     defaultValue: plan)
                     ]
                }
            }
        }
        stage("Apply / Destroy") {
            steps {
                dir("DB"){
                     sh '''
                  if [ "$TerraformAction" = "apply" ]; then
                    terraform apply -auto-approve tfplan
                    else
                    terraform destroy -auto-approve
                    fi
                '''
                }
            }
        }
        stage("Apply / Destroy") {
            steps {
                dir("DB"){
                     sh '''
                  if [ "$TerraformAction" = "apply" ]; then
                    terraform apply -auto-approve tfplan
                    else
                    terraform destroy -auto-approve
                    fi
                '''
                }
            }
        }
        stage("push to s3")
        steps{
            sh 'aws s3 cp tterraform.tfstate s3://arjun-ckm/db/backups/'
        }
    }
}