pipeline{
    agent any

    parameters {
        choice(name:"TerraformAction",choices:["apply","destroy"],description:"Terraform actions")
    }

    environment{
        AWS_ACCESS_KEY = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_KEY = credentials('AWS_SECRET_KEY')
    }

    stages{
        stage("checkout"){
            steps{
                git url: 'https://github.com/Gotoman12/DevOps-terraform.git',branch: 'Iac-Dev'
            }
               
        }
        stage("terraform-plan"){
            steps{
                sh 'cd vpc/; terraform init'
                sh 'cd vpc/; terraform validate'
                sh 'cd vpc/; terraform plan'
            }   
        }
        stage('Approval'){
            steps{
                script{
                    input message: "Do you want to proceed with the Terraform action?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
            }
        }
    }
}